routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\HomeController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ProjectController;
use App\Http\Controllers\CvStaffController;
use App\Http\Controllers\Staff_CategoryController;



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home');

Route::group(['middleware' => ['auth']], function() {
    Route::resource('roles', RoleController::class);
    Route::resource('users', UserController::class);
    Route::resource('products', ProductController::class);

    Route::any('projectList', [ProjectController::class, 'index'])->name('project');

    Route::get('project/create',[ProjectController::class, 'create'])->name('addProject');

    Route::post('insert',[ProjectController::class, 'insert'])->name('insertProjectinfo');

    Route::get('show/{id}',[ProjectController::class, 'show'])->name('showProject');

    Route::get('/project/{project}/edit', [ProjectController::class, 'edit'])->name('editProject');

    Route::post('/project/{project}/update', [ProjectController::class, 'update'])->name('updateProject');

    Route::get('/project/{project}/delete', [ProjectController::class, 'delete'])->name('deleteProject');

    Route::any('cvList', [CvStaffController::class, 'index'])->name('staffcv');

    Route::get('staffCV/create', [CvStaffController::class, 'create'])->name('addStaffcv'); 

    Route::get('/staffCV/{staffCV}/edit', [CvStaffController::class, 'edit'])->name('editStaffcv');

    Route::post('/staffCV/{staffCV}/update', [CvStaffController::class, 'update'])->name('updateStaffcv');

    Route::get('/staffCV/{staffCV}/delete', [CvStaffController::class, 'destroy'])->name('deleteStaffcv');

    Route::post('staffCV/insert', [CvStaffController::class, 'store'])->name('storeStaffcv');

    Route::any('CV/category', [Staff_CategoryController::class, 'index'])->name('category');

    Route::post('CV/category/insert', [Staff_CategoryController::class, 'store'])->name('storeCategory');

    Route::post('CV/category/{category}/update', [Staff_CategoryController::class, 'update'])->name('updateStaffcvCategory');

    Route::get('CV/category/{category}/edit', [Staff_CategoryController::class, 'edit'])->name('editStaffcvCategory');

    Route::get('CV/category/{category}/delete', [Staff_CategoryController::class, 'destroy'])->name('deleteStaffcvCategory');



  
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use HasFactory, Notifiable, HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UserController.php
<?php
    
namespace App\Http\Controllers;
    
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\User;
use Spatie\Permission\Models\Role;
use Illuminate\Support\Facades\URL;
use DB;
use Hash;
use Illuminate\Support\Arr;
    
class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $basenameUrl = basename(URL::current());
        $data = User::orderBy('id','DESC')->paginate(5);
        return view('users.index',compact('data','basenameUrl'))
            ->with('i', ($request->input('page', 1) - 1) * 5);
    }
    
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $basenameUrl = basename(URL::current());
        $roles = Role::pluck('name','name')->all();
        return view('users.create',compact('roles','basenameUrl'));
    }
    
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
            'email' => 'required|email|unique:users,email',
            'password' => 'required|same:confirm-password',
            'roles' => 'required'
        ]);
    
        $input = $request->all();
        $input['password'] = Hash::make($input['password']);
    
        $user = User::create($input);
        $user->assignRole($request->input('roles'));
    
        return redirect()->route('users.index')
                        ->with('success','User created successfully');
    }
    
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = User::find($id);
        return view('users.show',compact('user'));
    }
    
    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $basenameUrl = basename(URL::current());
        $user = User::find($id);
        $roles = Role::pluck('name','name')->all();
        $userRole = $user->roles->pluck('name','name')->all();
    
        return view('users.edit',compact('user','roles','userRole','basenameUrl'));
    }
    
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required',
            'email' => 'required|email|unique:users,email,'.$id,
            'password' => 'same:confirm-password',
            'roles' => 'required'
        ]);
    
        $input = $request->all();
        if(!empty($input['password'])){ 
            $input['password'] = Hash::make($input['password']);
        }else{
            $input = Arr::except($input,array('password'));    
        }
    
        $user = User::find($id);
        $user->update($input);
        DB::table('model_has_roles')->where('model_id',$id)->delete();
    
        $user->assignRole($request->input('roles'));
    
        return redirect()->route('users.index')
                        ->with('success','User updated successfully');
    }
    
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        User::find($id)->delete();
        return redirect()->route('users.index')
                        ->with('success','User deleted successfully');
    }
}

resources/views/users/create.blade.php
@extends('layouts.app')

@section('title', 'Users Create')


@section('js')

<script>

</script>


@endsection
@section('css')

@endsection


@section('content')
<!-- BEGIN CONTENT BODY -->
<div class="page-content">
    <!-- BEGIN PAGE HEADER-->

    @include('pages/include/beginPageHeader')

    {{-- @if ($errors->any())
                <div class="alert alert-danger">
                    <strong>Whoops!</strong> There were some problems with your input.<br><br>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
    @endforeach
    </ul>
</div>
@endif--}}
<!-- END PAGE HEADER-->
<div class="row">
    <div class="col-md-12">
        <div class="tabbable-line boxless tabbable-reversed">

            <div class="tab-content">
                <div class="tab-pane active" id="tab_0">

                    {{-- <div class="portlet box blue-hoki">--}}
                    <div class="portlet box blue">
                        <div class="portlet-title">
                            <div class="caption">
                                <i class="fa fa-gift"></i>User Form
                            </div>
                            <div class="actions">
                                <a class="btn btn-danger btn-icon-only btn-default" href="{{route('users.index')}}">
                                    <i class="fa fa-list bigger-130" style="color:#fff;"></i>
                                </a>
                                <a class="btn btn-danger btn-icon-only btn-default" href="#">
                                    <i class="fa fa-search-plus bigger-130" style="color:#fff;"></i>
                                </a>
                                <a class="btn btn-danger btn-icon-only btn-default" href="#">
                                    <i class="fa fa-pencil" style="color:#fff;"></i>
                                </a>
                                <a class="btn btn-danger btn-icon-only btn-default" href="#">
                                    <i class="fa fa-trash-o bigger-130" style="color:#fff;"></i>
                                </a>
                            </div>

                        </div>
                        <div class="portlet-body form">
                            <!-- BEGIN FORM-->



                            <form action="{{route('users.store')}}" method="post" class="form-horizontal" enctype="multipart/form-data">
                                @csrf
                                <div class="form-body">
                                    <div class="form-group">
                                        <label class="col-md-3 control-label">User Name</label>
                                        <div class="col-md-4">
                                            <input name="name" value="{{ old('name') }}" type="text" class="form-control" placeholder="Enter User Name">


                                            {!! $errors->first('name', '<small class="text-danger">:message</small>') !!}
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label class="col-md-3 control-label">User Email</label>
                                        <div class="col-md-4">
                                            <input name="email" value="{{ old('email') }}" type="email" class="form-control" placeholder="Enter User Email">


                                            {!! $errors->first('email', '<small class="text-danger">:message</small>') !!}
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label class="col-md-3 control-label">User Phone</label>
                                        <div class="col-md-4">
                                            <input name="phone" value="{{ old('phone') }}" type="phone" class="form-control" placeholder="Enter User Phone">


                                            {!! $errors->first('phone', '<small class="text-danger">:message</small>') !!}
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label class="col-md-3 control-label">User Password</label>
                                        <div class="col-md-4">
                                            <input name="password" value="{{ old('password') }}" type="password" class="form-control" placeholder="Enter User password">

                                            {!! $errors->first('password', '<small class="text-danger">:message</small>') !!}
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label class="col-md-3 control-label">User Confirm Password</label>
                                        <div class="col-md-4">
                                            <input name="confirm-password" value="{{ old('confirm-password') }}" type="password" class="form-control" placeholder="Enter Confirm Password">

                                            {!! $errors->first('confirm-password', '<small class="text-danger">:message</small>') !!}
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label class="col-md-3 control-label">Role</label>
                                        <div class="col-md-4">
                                            <select id="single" name="roles" class="form-control select2">
                                                <option value=""></option>
                                                @foreach($roles as $role)
                                                <option value="{{$role}}">{{$role}}</option>
                                                @endforeach

                                            </select>
                                            {!! $errors->first('roles', '<small class="text-danger">:message</small>') !!}
                                        </div>
                                    </div>



                                </div>

                                <div class="form-actions top">
                                    <div class="row">
                                        <div class="col-md-offset-4 col-md-8">
                                            <button type="submit" class="btn green">Submit</button>
                                            <button type="button" class="btn default">Cancel</button>
                                        </div>
                                    </div>
                                </div>
                            </form>
                            <!-- END FORM-->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


</div>
<!-- END CONTENT BODY -->
@endsection

resources/views/users/edit.blade.php
@extends('layouts.app')

@section('title', 'Users Create')


@section('js')

<script>

</script>


@endsection
@section('css')

@endsection


@section('content')
<!-- BEGIN CONTENT BODY -->
<div class="page-content">
    <!-- BEGIN PAGE HEADER-->

    @include('pages/include/beginPageHeader')

    {{-- @if ($errors->any())
                <div class="alert alert-danger">
                    <strong>Whoops!</strong> There were some problems with your input.<br><br>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
    @endforeach
    </ul>
</div>
@endif--}}
<!-- END PAGE HEADER-->
<div class="row">
    <div class="col-md-12">
        <div class="tabbable-line boxless tabbable-reversed">

            <div class="tab-content">
                <div class="tab-pane active" id="tab_0">

                    {{-- <div class="portlet box blue-hoki">--}}
                    <div class="portlet box blue">
                        <div class="portlet-title">
                            <div class="caption">
                                <i class="fa fa-gift"></i>User Edit Form
                            </div>
                            <div class="actions">
                                <a class="btn btn-danger btn-icon-only btn-default" href="{{route('users.index')}}">
                                    <i class="fa fa-list bigger-130" style="color:#fff;"></i>
                                </a>
                                <a class="btn btn-danger btn-icon-only btn-default" href="#">
                                    <i class="fa fa-search-plus bigger-130" style="color:#fff;"></i>
                                </a>
                                <a class="btn btn-danger btn-icon-only btn-default" href="#">
                                    <i class="fa fa-pencil" style="color:#fff;"></i>
                                </a>
                                <a class="btn btn-danger btn-icon-only btn-default" href="#">
                                    <i class="fa fa-trash-o bigger-130" style="color:#fff;"></i>
                                </a>
                            </div>

                        </div>
                        <div class="portlet-body form">
                            <!-- BEGIN FORM-->


                            <form action="{{route('users.update',$user->id)}}" method="post" class="form-horizontal" enctype="multipart/form-data">

                                {{ method_field('PATCH') }}
                                {{ csrf_field() }}

                                <div class="form-body">
                                    <div class="form-group">
                                        <label class="col-md-3 control-label">User Name</label>
                                        <div class="col-md-4">
                                            <input name="name" value="{{ $user->name }}" type="text" class="form-control" placeholder="Enter User Name">


                                            {!! $errors->first('name', '<small class="text-danger">:message</small>') !!}
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label class="col-md-3 control-label">User Email</label>
                                        <div class="col-md-4">
                                            <input name="email" value="{{ $user->email }}" type="email" class="form-control" placeholder="Enter User Email">


                                            {!! $errors->first('email', '<small class="text-danger">:message</small>') !!}
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label class="col-md-3 control-label">User Phone</label>
                                        <div class="col-md-4">
                                            <input name="phone" value="{{ $user->phone }}" type="number" class="form-control" placeholder="Enter User Phone">


                                            {!! $errors->first('phone', '<small class="text-danger">:message</small>') !!}
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label class="col-md-3 control-label">User Password</label>
                                        <div class="col-md-4">
                                            <input name="password" value="{{ old('password') }}" type="password" class="form-control" placeholder="Enter User password">


                                            {!! $errors->first('password', '<small class="text-danger">:message</small>') !!}
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label class="col-md-3 control-label">User Confirm Password</label>
                                        <div class="col-md-4">
                                            <input name="confirm-password" value="{{ old('confirm-password') }}" type="password" class="form-control" placeholder="Enter Confirm Password">


                                            {!! $errors->first('confirm-password', '<small class="text-danger">:message</small>') !!}
                                        </div>
                                    </div>


                                    <div class="form-group">

                                        <label class="col-md-3 control-label">Role </label>
                                        <div class="col-md-4">
                                            <select id="single" name="roles" class="form-control select2">
                                                <option value=""></option>

                                                @foreach($roles as $item)

                                                @foreach($userRole as $value)
                                                <option value="{{$item}}" {{ $item == $value ? 'selected' : '' }}>{{$item}}</option>
                                                @endforeach

                                                @endforeach


                                            </select>
                                            {!! $errors->first('roles', '<small class="text-danger">:message</small>') !!}
                                        </div>
                                    </div>


                                </div>

                                <div class="form-actions top">
                                    <div class="row">
                                        <div class="col-md-offset-4 col-md-8">
                                            <button type="submit" class="btn green">Submit</button>
                                            <button type="button" class="btn default">Cancel</button>
                                        </div>
                                    </div>
                                </div>
                            </form>
                            <!-- END FORM-->
                        </div>
                    </div>


                </div>


            </div>
        </div>
    </div>
</div>


</div>
<!-- END CONTENT BODY -->
@endsection

resources/views/users/index.blade.php
@extends('layouts.app')

@section('title', 'Users List')


@section('js')


@endsection
@section('css')
<style>
    .portlet.box .dataTables_wrapper .dt-buttons {
        margin-top: 0px;
    }

    .dataTables_wrapper .dt-buttons {
        float: left;
    }

    div.dataTables_wrapper div.dataTables_paginate {
        /* margin: 0; */
        white-space: nowrap;
        /* text-align: right; */
        float: right !important;
    }

    .input-group-sm>.input-group-btn>select.btn,
    .input-group-sm>select.form-control,
    .input-group-sm>select.input-group-addon,
    select.input-sm {
        height: 31px;
        line-height: 30px;
    }
</style>
@endsection


@section('content')

<!-- BEGIN CONTENT BODY -->
<div class="page-content">
    <!-- BEGIN PAGE HEADER-->


    @include('pages.include.beginPageHeader')


    <!-- END PAGE HEADER-->

    <div class="row">
        <div class="col-md-12">


            <!-- BEGIN EXAMPLE TABLE PORTLET-->
            <div class="portlet box green">
                <div class="portlet-title">

                    <div class="dt-buttons" style="margin-top: 5px;">
                        <a class="dt-button buttons-print btn default" tabindex="0" aria-controls="example" href="{{ route('users.create') }}"><span> <i class="fa fa-plus"></i> Create New User</span>

                        </a>
                    </div>

                </div>


                <div class="portlet-body">

                    <table class="table table-striped table-bordered table-hover" id="example">

                        <thead>

                            <tr>
                                <th>No</th>
                                <th>Name</th>
                                <th>Email</th>
                                <th width="280px">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                           @foreach ($data as $key => $item)
                            <tr>
                                <td>{{ ++$i }}</td>
                                <td>{{ $item->name }}</td>
                                <td>{{ $item->email }}</td>
                                <td>
                                    <a class="btn btn-info" href="{{ route('users.show',$item->id) }}">Show</a>
                                  
                                    <a class="btn btn-primary" href="{{ route('users.edit',$item->id) }}">Edit</a>
                                    
                                    @can('users-delete')
                                    {!! Form::open(['method' => 'DELETE','route' => ['users.destroy', $item->id],'style'=>'display:inline']) !!}
                                    {!! Form::submit('Delete', ['class' => 'btn btn-danger']) !!}
                                    {!! Form::close() !!}
                                    @endcan
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
            <!-- END EXAMPLE TABLE PORTLET-->
        </div>
    </div>

</div>
{{--{!! $data->render() !!}--}}
<!-- END CONTENT BODY -->
@endsection

resources/views/users/show.blade.php
@extends('layouts.app')


@section('content')
<div class="page-content">
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2> Show User</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('users.index') }}"> Back</a>
            </div>
        </div>
    </div>


    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Name:</strong>
                {{ $user->name }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Email:</strong>
                {{ $user->email }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Roles:</strong>
                @if(!empty($user->getRoleNames()))
                @foreach($user->getRoleNames() as $v)
                <label class="badge badge-success">{{ $v }}</label>
                @endforeach
                @endif
            </div>
        </div>
    </div>
</div>

@endsection